"""Identifiability-aware source apportionment primitives."""

from model.iasa.backend import (
    ENSEMBLE_KINDS,
    INVERSE_DTYPE,
    RESPONSE_DTYPE,
    runtime_provenance,
    tensor_hash,
    to_numpy,
    validate_ensemble_kind,
)
from model.iasa.background import BackgroundBasisConfig, BackgroundBasisResult, build_background_basis
from model.iasa.diagnostics import (
    DiagnosticsConfig,
    DiagnosticsResult,
    diagnose_identifiability,
    diagnose_projection,
    summarize_wind_ensemble,
)
from model.iasa.fit import (
    AdequacyConfig,
    AdequacyResult,
    FitConfig,
    FitResult,
    NoiseModel,
    aggregate_inventory_scenarios,
    aggregate_transport_ensemble,
    fit_projection,
    fit_sources,
    residual_adequacy_check,
    summarize_report_groups,
)
from model.iasa.merge import (
    MergeConfig,
    MergeResult,
    recommend_merges,
)
from model.iasa.footprints import (
    FootprintResult,
    compute_sensor_footprints,
    decompose_per_sensor,
    per_sensor_identifiability,
)
from model.iasa.projection import (
    BackgroundProjector,
    ProjectionConfig,
    ProjectionResult,
    fit_background_projector,
    project_response_and_observations,
)

from model.iasa.response import (
    BOUNDARY_MODE,
    RESPONSE_IMPLEMENTATION,
    CityWindSampler,
    DispersionConfig,
    GriddedWindSampler,
    Observer,
    ResponseConfig,
    ResponseMatrixResult,
    WindSampler,
    build_lagged_response_matrix,
)
from model.iasa.wind import (
    CoordinateQueryImputer,
    GriddedWindField,
    KernelCoordinateQueryImputer,
    build_gridded_wind_field,
    build_wind_field_ensemble,
    evaluate_gridded_wind_heldout,
    gridded_new_delhi_wind_field,
    transport_vectors_from_wd_ws,
)
from model.iasa.fieldformer_adapter import (
    FieldFormerCoordinateQueryImputer,
    build_fieldformer_wind_imputer,
    build_untrained_wind_model,
)

__all__ = [
    "BOUNDARY_MODE",
    "ENSEMBLE_KINDS",
    "INVERSE_DTYPE",
    "RESPONSE_DTYPE",
    "RESPONSE_IMPLEMENTATION",
    "runtime_provenance",
    "tensor_hash",
    "to_numpy",
    "validate_ensemble_kind",
    "BackgroundBasisConfig",
    "BackgroundBasisResult",
    "BackgroundProjector",
    "DiagnosticsConfig",
    "DiagnosticsResult",
    "diagnose_identifiability",
    "diagnose_projection",
    "summarize_wind_ensemble",
    "AdequacyConfig",
    "AdequacyResult",
    "FitConfig",
    "FitResult",
    "NoiseModel",
    "aggregate_inventory_scenarios",
    "aggregate_transport_ensemble",
    "fit_projection",
    "fit_sources",
    "residual_adequacy_check",
    "summarize_report_groups",
    "MergeConfig",
    "MergeResult",
    "recommend_merges",
    "FootprintResult",
    "compute_sensor_footprints",
    "decompose_per_sensor",
    "per_sensor_identifiability",
    "CityWindSampler",
    "DispersionConfig",
    "GriddedWindSampler",
    "Observer",
    "ProjectionConfig",
    "ProjectionResult",
    "ResponseConfig",
    "ResponseMatrixResult",
    "WindSampler",
    "CoordinateQueryImputer",
    "GriddedWindField",
    "KernelCoordinateQueryImputer",
    "FieldFormerCoordinateQueryImputer",
    "build_fieldformer_wind_imputer",
    "build_untrained_wind_model",
    "build_gridded_wind_field",
    "build_wind_field_ensemble",
    "evaluate_gridded_wind_heldout",
    "gridded_new_delhi_wind_field",
    "transport_vectors_from_wd_ws",
    "build_background_basis",
    "build_lagged_response_matrix",
    "fit_background_projector",
    "project_response_and_observations",
]
